// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0QtYHc_9Cy-Fr6_0mm4pXcQ1YF2clzGE',
    appId: '1:593690288781:web:d2f8dd2028a5853d7738c4',
    messagingSenderId: '593690288781',
    projectId: 'flippa-18c94',
    authDomain: 'flippa-18c94.firebaseapp.com',
    storageBucket: 'flippa-18c94.firebasestorage.app',
    measurementId: 'G-HW4MJLQGQS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRXWszZZmbmsNXS6FLuAgEd2kkYsRQgm4',
    appId: '1:593690288781:android:2a6bd779d4b666067738c4',
    messagingSenderId: '593690288781',
    projectId: 'flippa-18c94',
    storageBucket: 'flippa-18c94.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA04kn-pLdeP5jRY1KIe6bjT0Ko1mRKx9w',
    appId: '1:593690288781:ios:3cfd207fa4aa58d27738c4',
    messagingSenderId: '593690288781',
    projectId: 'flippa-18c94',
    storageBucket: 'flippa-18c94.firebasestorage.app',
    androidClientId: '593690288781-uuru4to8hq90nnoilm6ook6rbg0qva1e.apps.googleusercontent.com',
    iosClientId: '593690288781-ga444v0t8i7ehs3ajo53o3j1r7o1b44o.apps.googleusercontent.com',
    iosBundleId: 'com.xerxes.flippa.flippa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA04kn-pLdeP5jRY1KIe6bjT0Ko1mRKx9w',
    appId: '1:593690288781:ios:3cfd207fa4aa58d27738c4',
    messagingSenderId: '593690288781',
    projectId: 'flippa-18c94',
    storageBucket: 'flippa-18c94.firebasestorage.app',
    androidClientId: '593690288781-uuru4to8hq90nnoilm6ook6rbg0qva1e.apps.googleusercontent.com',
    iosClientId: '593690288781-ga444v0t8i7ehs3ajo53o3j1r7o1b44o.apps.googleusercontent.com',
    iosBundleId: 'com.xerxes.flippa.flippa',
  );
}
